// components/code/index.jsx
import React, { useState } from 'react';
import propTypes from 'prop-types';
import { Copy, Check } from 'react-feather';
import useStyles from './styles';
import { convertStylesToCss, unionClassNames } from '../utils/helpers';

const Code = ({ children, style, code, inline, beforeIcon: BeforeIcon, afterIcon: AfterIcon, ...props }) => {
  const jssCSS = useStyles();
  const inlineCSS = convertStylesToCss(style);

  const [status, setStatus] = useState('');

  function copyCode() {
    navigator.clipboard.writeText(code || children)
      .then(() => {
        setStatus('active');
        setTimeout(() => setStatus(''), 1000);
      });
  }

  const codeMultiLine = (
    <pre className={unionClassNames(jssCSS.code, inlineCSS, status)} {...props}>
      <button type="button" aria-label="Copy" onClick={copyCode}>
        {!status
          ? <BeforeIcon size={20} strokeWidth={1} />
          : <AfterIcon size={20} strokeWidth={1} /> }
      </button>
      <code>{code || children}</code>
    </pre>
  );

  const codeInline = (
    // eslint-disable-next-line jsx-a11y/click-events-have-key-events
    <code
      className={unionClassNames(jssCSS.codeInline, inlineCSS, status)}
      onClick={copyCode}
      role="button"
      tabIndex={0}
      {...props}
    >
      {code || children}
    </code>
  );

  return !inline
    ? codeMultiLine
    : codeInline;
};

Code.propTypes = {
  children: propTypes.string,
  /** Inline Styles assigned to the component will be converted to CSS class */
  style: propTypes.oneOfType([propTypes.object]),
  /** Submits the source code to be displayed */
  code: propTypes.string,
  /** Should the source code be mapped to a string */
  inline: propTypes.bool,
  /** Changes the icon until the button is clicked */
  beforeIcon: propTypes.node,
  /** Changes the icon after clicking on the button */
  afterIcon: propTypes.node,
};

Code.defaultProps = {
  children: '',
  style: null,
  code: '',
  inline: false,
  beforeIcon: Copy,
  afterIcon: Check,
};

export default Code;

// packages/vue/src/code.jsx
/* eslint-disable vue/no-reserved-props */
import { defineComponent, inject, ref } from 'vue';
import { Code as CodeCss } from '@wuki-ui/css';
import { Copy, Check } from 'lucide-vue-next';
import { combineClass, convertStyle } from '@wuki-ui/utils';

const Grid = defineComponent({
  components: {
    Copy,
    Check,
  },
  props: {
    style: {
      type: Object,
      default: null,
    },
    inline: {
      type: Boolean,
      default: false,
    },
    beforeIcon: {
      // type: String,
      default: () => <Copy size={20} stroke-width={1} />,
    },
    afterIcon: {
      // type: String,
      default: () => <Check size={20} stroke-width={1} />,
    },
  },
  setup({
    style, inline, beforeIcon, afterIcon,
  }, { slots }) {
    const theme = inject('theme');
    const { classes } = CodeCss(theme);
    const inlineCss = convertStyle(style);

    const status = ref('disable');

    function copyCode() {
      navigator.clipboard.writeText(slots.default()[0].children)
        .then(() => {
          status.value = 'active';
          setTimeout(() => { status.value = 'disable'; }, 1000);
        });
    }

    const codeMultiLine = () => (
      <pre class={combineClass(classes.code, inlineCss, status.value)}>
        <button type="button" aria-label="Copy" onClick={copyCode}>
          {status.value !== 'active'
            ? <beforeIcon />
            : <afterIcon />
          }
        </button>
        <code>{slots.default()}</code>
      </pre>
    );

    const codeInline = () => (
      <code
        class={combineClass(classes.codeInline, inlineCss, status.value)}
        onClick={copyCode}
        role="button"
        tabIndex={0}
      >
        {slots.default()}
      </code>
    );

    return inline
      ? codeInline
      : codeMultiLine;
  },
});

export default Grid;
