// components/grid/index.jsx
/* eslint-disable no-restricted-syntax */
import React, { useEffect, useState } from 'react';
import propTypes from 'prop-types';
import useStyles from './styles';
import { convertStylesToCss, unionClassNames } from '../utils/helpers';

const Grid = ({ children, tag: Tag, col, offset, container, style }) => {
  useStyles();
  const inlineCSS = convertStylesToCss(style);

  const [classCol, setClassCol] = useState('');
  const [classOffset, setClassOffset] = useState('');
  const [classContainer, setClassContainer] = useState('');

  /**
   * Creates and returns a className col
   */
  const classNameCol = () => {
    if (typeof col === 'object') {
      let a = '';
      for (const [bpKey, bpValue] of Object.entries(col)) {
        a = `${a} wk-col-${bpKey}-${bpValue}`;
      }
      setClassCol(a);
    } else {
      setClassCol(`wk-col-xs-${col}`);
    }
  };

  /**
   * Creates and returns a class Name offset
   */
  const classNameOffset = () => {
    if (offset) {
      setClassOffset(`wk-offset-${offset}`);
    }
  };

  useEffect(() => {
    if (container) {
      setClassContainer('wk-con');
    } else {
      classNameCol();
      classNameOffset();
    }
  }, [container, col, offset]);

  return (
    <Tag className={unionClassNames(classCol, classOffset, classContainer, inlineCSS)}>{children}</Tag>
  );
};

Grid.propTypes = {
  children: propTypes.node,
  /** Inline Styles assigned to the component will be converted to CSS class */
  style: propTypes.oneOfType([
    propTypes.string,
    propTypes.number,
  ]),
  /** For better semantics, you can override the default HTML tag */
  tag: propTypes.string,
  col: propTypes.oneOfType([propTypes.number, propTypes.object]),
  offset: propTypes.number,
  container: propTypes.bool,
};

Grid.defaultProps = {
  children: '',
  style: null,
  tag: 'div',
  col: 1,
  offset: null,
  container: false,
};

export default Grid;

// packages/vue/src/grid.jsx
/* eslint-disable vue/no-reserved-props */
import { defineComponent, inject, ref } from 'vue';
import { Grid as GridCss } from '@wuki-ui/css';
import { combineClass, convertStyle } from '@wuki-ui/utils';

const Grid = defineComponent({
  props: {
    style: {
      type: Object,
      default: null,
    },
    tag: {
      type: String,
      default: 'div',
    },
    col: {
      type: [Number, Object],
      default: 1,
    },
    offset: {
      type: Number,
      default: null,
    },
    container: {
      type: Boolean,
      default: false,
    },
  },
  setup({
    style, tag: Tag, col, offset, container,
  }, { slots }) {
    const theme = inject('theme');
    const { classes } = GridCss(theme);
    const inlineCss = convertStyle(style);

    const classCol = ref('');
    const classOffset = ref('');
    const classContainer = ref('');

    if (container) {
      classContainer.value = classes.con;
    } else {
      /**
       * Creates and returns a className col
       */
      if (typeof col === 'object') {
        classCol.value = Object.entries(col).reduce((acc, [key, value]) => {
          acc.push(classes[`col-${key}-${value}`]);
          return acc;
        }, []).join(' ');
      } else {
        classCol.value = classes[`col-xs-${col}`];
      }

      /**
       * Creates and returns a class Name offset
       */
      if (offset) {
        classOffset.value = classes[`offset-${offset}`];
      }
    }

    return () => (
      <Tag class={combineClass(classCol.value, classOffset.value, classContainer.value, inlineCss)}>
        {slots.default()}
      </Tag>
    );
  },
});

export default Grid;
