// packages/react/src/text.jsx
import React, { useEffect, useState } from 'react';
import propTypes from 'prop-types';
import { Text as TextCss } from '@wuki-ui/css';
import { combineClass, convertStyle } from '@wuki-ui/utils';
import { useContextWuki } from './provider';

function Text({
  children, style, tag: Tag, variant, ...props
}) {
  const theme = useContextWuki();
  const { classes } = TextCss(theme);
  const inlineCss = convertStyle(style);

  const [classVariant, setClassVariant] = useState('');

  useEffect(() => {
    if (Object.keys(classes).includes(Tag)) {
      setClassVariant(classes[variant] || classes[Tag]);
    } else {
      setClassVariant(classes[variant]);
    }
  }, [Tag, variant]);

  return <Tag className={combineClass(classVariant, inlineCss)} {...props}>{children}</Tag>;
}

Text.propTypes = {
  children: propTypes.node,
  /** Inline Styles assigned to the component will be converted to CSS class */
  style: propTypes.oneOfType([propTypes.object]),
  /** For better semantics, you can override the default HTML tag */
  tag: propTypes.string,
  /** Allows you to tell the component to use any variation from the theme */
  variant: propTypes.string,
};

Text.defaultProps = {
  children: '',
  style: null,
  tag: 'p',
  variant: '',
};

export default Text;

// packages/vue/src/text.jsx
/* eslint-disable vue/no-reserved-props */
import { defineComponent, inject, ref } from 'vue';
import { Text as TextCss } from '@wuki-ui/css';
import { combineClass, convertStyle } from '@wuki-ui/utils';

const Text = defineComponent({
  props: {
    style: {
      type: Object,
      default: null,
    },
    tag: {
      type: String,
      default: 'p',
    },
    variant: {
      type: String,
      default: '',
    },
  },
  setup({ style, tag, variant }, { slots }) {
    const theme = inject('theme');
    const { classes } = TextCss(theme);
    const inlineCss = convertStyle(style);

    let classVariant = ref('');

    if (Object.keys(classes).includes(tag)) {
      classVariant = classes[variant] || classes[tag];
    } else {
      classVariant = classes[variant];
    }

    return () => <tag class={combineClass(classVariant, inlineCss)}>{slots.default()}</tag>;
  },
});

export default Text;
